name: flutter_liquid_glass_tab_bar_example
description: Demo app for flutter_liquid_glass_tab_bar.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_liquid_glass_tab_bar:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
